import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Drone Delivery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Drone Delivery</h1>

        <form
          className="flex flex-col border border-gray-100 shadow-md p-5 rounded-sm mt-5"
          action=""
        >
          <label htmlFor="name">Name</label>
          <input className="bg-gray-100 rounded-md" id="name" type="text" />
          <label htmlFor="address">Address</label>
          <input className="bg-gray-100 rounded-md" id="address" type="text" />
          <button className="bg-blue-500 text-gray-100 px-4 py-2 rounded-md mt-5">
            Get Started
          </button>
        </form>
      </main>
    </div>
  );
}
