import Head from "next/head";

import styles from "@/styles/Home.module.css";
import Form from "@/components/Form";

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Drone Delivery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="flex flex-col items-center">
          <h1 className="text-3xl">Drone Delivery</h1>
          <p className="mt-2">
            Get started with our new drone delivery service today!
          </p>
        </div>

        <Form />

        <div>
          <p className="bg-red-100 text-red-500 px-4 py-1 rounded-full mt-5 border border-red-500">
            Error message here!
          </p>
        </div>
      </main>
    </div>
  );
}
